-- ============================================================
-- Crenelle — Paystack Payment Infrastructure
-- Migration: 032_paystack_payment_infrastructure.sql
-- ============================================================
--
-- Adds:
--   1. organizer_payment_settings  — per-organiser Paystack subaccount + bank details
--   2. payments                    — one row per payment attempt (full audit trail)
--
-- Alters:
--   invitations — adds payment_status, amount_paid_kobo, paid_at
--
-- Safe to run on a live database:
--   • All new columns are nullable or have defaults.
--   • No existing indexes or triggers are removed.
--   • Uses IF NOT EXISTS throughout.
-- ============================================================

-- ── 1. organizer_payment_settings ────────────────────────────

CREATE TABLE IF NOT EXISTS public.organizer_payment_settings (
  id                      uuid          DEFAULT gen_random_uuid() PRIMARY KEY,
  organizer_id            uuid          NOT NULL UNIQUE
                                        REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Paystack subaccount (null until organiser connects their bank)
  paystack_subaccount_code text,        -- e.g. ACCT_xxxxxxxxxxxxxxxx
  -- Bank details (stored after account resolution)
  bank_name               text,
  bank_code               text,         -- Paystack bank code, e.g. '058' for GTBank
  account_number          text,
  account_name            text,         -- resolved display name from Paystack
  -- Status
  is_verified             boolean       NOT NULL DEFAULT false,
  -- Fee split: Crenelle's platform commission percentage
  -- Organiser receives (100 - platform_fee_percent)% of net amount
  platform_fee_percent    numeric(5,2)  NOT NULL DEFAULT 5.00
                                        CHECK (platform_fee_percent >= 0 AND platform_fee_percent <= 100),
  connected_at            timestamptz,
  created_at              timestamptz   NOT NULL DEFAULT now(),
  updated_at              timestamptz   NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.organizer_payment_settings IS
  'Stores each organiser''s Paystack subaccount and bank details for split payment settlement.';

COMMENT ON COLUMN public.organizer_payment_settings.paystack_subaccount_code IS
  'Paystack subaccount code (ACCT_xxx). Null until the organiser connects their bank account.';

COMMENT ON COLUMN public.organizer_payment_settings.platform_fee_percent IS
  'Crenelle''s commission percentage. Organiser receives (100 - this)% of each transaction''s net amount.';

-- ── 2. payments ───────────────────────────────────────────────

-- payment_status enum-like domain via CHECK (avoids ENUM migration complexity)
CREATE TABLE IF NOT EXISTS public.payments (
  id                      uuid          DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id                uuid          NOT NULL
                                        REFERENCES public.events(id) ON DELETE RESTRICT,
  attendee_id             uuid
                                        REFERENCES public.attendees(id) ON DELETE SET NULL,
  ticket_tier_id          uuid
                                        REFERENCES public.ticket_tiers(id) ON DELETE SET NULL,
  -- Paystack identifiers
  paystack_reference      text          NOT NULL UNIQUE,  -- our generated reference (CRN-xxx)
  paystack_transaction_id bigint,                         -- Paystack's internal transaction ID
  -- Amounts — all stored in kobo (NGN × 100)
  amount_kobo             integer       NOT NULL CHECK (amount_kobo > 0),
  platform_fee_kobo       integer       CHECK (platform_fee_kobo >= 0),
  organiser_amount_kobo   integer       CHECK (organiser_amount_kobo >= 0),
  currency                text          NOT NULL DEFAULT 'NGN',
  -- Status lifecycle
  status                  text          NOT NULL DEFAULT 'pending'
                                        CHECK (status IN ('pending', 'paid', 'failed', 'refunded', 'abandoned')),
  -- Payer info (captured at point of payment)
  payer_email             text          NOT NULL,
  payer_name              text,
  -- Paystack channel: card, bank, ussd, bank_transfer, qr
  paystack_channel        text,
  -- Flexible metadata: tier name, event name, etc. (for receipts & dispute evidence)
  metadata                jsonb,
  -- Timestamps
  webhook_received_at     timestamptz,
  paid_at                 timestamptz,
  created_at              timestamptz   NOT NULL DEFAULT now(),
  updated_at              timestamptz   NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.payments IS
  'Full audit trail for every Paystack transaction. One row per payment attempt.';

COMMENT ON COLUMN public.payments.paystack_reference IS
  'Unique reference generated by Crenelle (format: CRN-{eventId8}-{timestamp}). Sent to Paystack on initialize.';

COMMENT ON COLUMN public.payments.amount_kobo IS
  'Total amount the guest was charged, in kobo (NGN amount × 100). Verified against Paystack webhook.';

-- ── 3. Extend invitations table ───────────────────────────────

-- payment_status on the invitation (denormalised for fast dashboard queries)
ALTER TABLE public.invitations
  ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'unpaid'
    CHECK (payment_status IN ('unpaid', 'paid', 'refunded', 'failed')),
  ADD COLUMN IF NOT EXISTS amount_paid_kobo integer,
  ADD COLUMN IF NOT EXISTS paid_at timestamptz;

COMMENT ON COLUMN public.invitations.payment_status IS
  'Denormalised payment state for dashboard display. Source of truth is the payments table.';

-- ── 4. Indexes ────────────────────────────────────────────────

-- organizer_payment_settings
CREATE INDEX IF NOT EXISTS organizer_payment_settings_organizer_id_idx
  ON public.organizer_payment_settings (organizer_id);

-- payments
CREATE INDEX IF NOT EXISTS payments_event_id_idx
  ON public.payments (event_id);

CREATE INDEX IF NOT EXISTS payments_reference_idx
  ON public.payments (paystack_reference);

CREATE INDEX IF NOT EXISTS payments_status_idx
  ON public.payments (status);

CREATE INDEX IF NOT EXISTS payments_attendee_id_idx
  ON public.payments (attendee_id);

CREATE INDEX IF NOT EXISTS payments_paid_at_idx
  ON public.payments (paid_at)
  WHERE paid_at IS NOT NULL;

-- invitations: partial index for quick unpaid lookup
CREATE INDEX IF NOT EXISTS invitations_payment_status_idx
  ON public.invitations (payment_status)
  WHERE payment_status = 'unpaid';

-- ── 5. RLS — organizer_payment_settings ───────────────────────

ALTER TABLE public.organizer_payment_settings ENABLE ROW LEVEL SECURITY;

-- Organisers manage their own settings only
CREATE POLICY "Organisers manage their own payment settings"
  ON public.organizer_payment_settings FOR ALL
  USING (organizer_id = auth.uid())
  WITH CHECK (organizer_id = auth.uid());

-- ── 6. RLS — payments ─────────────────────────────────────────

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Organisers can read payments for events they own
CREATE POLICY "Organisers can read payments for their events"
  ON public.payments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.events e
      WHERE e.id = payments.event_id
        AND e.organizer_id = auth.uid()
    )
  );

-- Co-hosts with any role can read payment data for events they are members of
CREATE POLICY "Members can read payments for co-hosted events"
  ON public.payments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.event_members em
      WHERE em.event_id = payments.event_id
        AND em.member_id = auth.uid()
    )
  );

-- No direct INSERT/UPDATE from authenticated users — all writes go through
-- the webhook handler and payment actions which use the admin (service-role) client.

-- ── 7. updated_at triggers ────────────────────────────────────

-- Reuse the pattern if a generic updated_at trigger function exists,
-- otherwise create a local one scoped to these two tables.

DO $$
BEGIN
  -- Create function only if it doesn't already exist (may exist from earlier migrations)
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = 'set_updated_at'
  ) THEN
    EXECUTE $func$
      CREATE OR REPLACE FUNCTION public.set_updated_at()
      RETURNS TRIGGER LANGUAGE plpgsql AS $$
      BEGIN
        NEW.updated_at = now();
        RETURN NEW;
      END;
      $$;
    $func$;
  END IF;
END;
$$;

CREATE TRIGGER payments_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER organizer_payment_settings_updated_at
  BEFORE UPDATE ON public.organizer_payment_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
